# Generated by Django 3.2.13 on 2022-11-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.TextField()),
                ('date_opened', models.DateTimeField()),
                ('overview', models.TextField()),
                ('trailer_key', models.TextField()),
                ('review_searched', models.TextField()),
                ('genres_of_movie', models.ManyToManyField(related_name='movies_of_genre', to='movies.Genre')),
                ('starring', models.ManyToManyField(related_name='filmography', to='movies.Actor')),
            ],
        ),
    ]
