# Generated by Django 3.2.13 on 2022-11-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actor_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
