# Generated by Django 4.1.3 on 2022-11-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
