# Generated by Django 4.1.3 on 2022-11-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review_searched',
        ),
        migrations.CreateModel(
            name='ReviewVideo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('video_title', models.TextField()),
                ('video_id', models.TextField()),
                ('video_date', models.TextField()),
                ('channel_name', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
