# Generated by Django 4.1.3 on 2022-11-22 06:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review_searched',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
    ]
