# Generated by Django 4.1.3 on 2022-11-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_review_searched_reviewvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewvideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
