# Generated by Django 4.1.3 on 2022-11-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
