# Generated by Django 4.1.3 on 2022-11-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
